---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}] #needed for http tests since inspec executes locally
    - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}] #needed for http tests since inspec executes locally

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.1

suites:
  - name: default
    run_list:
      - recipe[codenamephp_apache2::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
