driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current
  ports:
    - '8080:80' #needed for http tests since inspec executes locally
    - '8443:443' #needed for http tests since inspec executes locally

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
 
platforms:
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
