language: ruby
sudo: required
dist: trusty

branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  
services: docker

env:
  global:
    - ENV="ci"
    - secure: "CgWhqCkNrDoWDCNrZnEOQiwCcEnat81zYB0omZoFHHKfLQxaw9M9dnuzlhwAh/VLvhj5z0G7IwT45V4EE7zljzvpFl9iA63IpMfIQWbUdV7J33nc0lau9vy5awL1WGujxCA24syKvIYXNFis7l5pJSzz3YaszbIcfmDcXVapBCQpX5R5xrr4f+qASwVNCTrpdx0+r6+UK/O/74dTzGc/BYYHNU4T2zcx5VDc+SfkYXrl4cxQynJ3Ps00iwYCFwqbCF2Lwi34AnG1MT1I7RXQ8pZQrWO4uRUfOtfTLpCwO0qGOhkTK4ZE2NbBSF6o+BlGiw0YlHsMuiv9fBtjAoW2nPtxEcKU5+knbrrnx1TQfjYzIurOYhbcRHcNBAGfzoQ0sU2qwp+9l5cCYp+D1n3L309X0YC3sTrfhAaZtWZjDSq6jfg+cWIx/oofvBdevwxR2yzlQSw4vTBHmcS75FnAjQPpbDxNWtVb70cVminOevbsh89gUF+8scu8vGgkrzJuIIKQ74fAm2D4/KtoEI4Y85oCTJoz5n0mNePJQecz5w6JsaXMLc+arE8HPvc7TwauV/1SgsZE2S5DqgrBZLTM0VtA9pzPeUKCTeisLqEWO5g7+LaYelkNmr0M1ByiKZUD/pBRGFjQm+6wZZEmLO5Z193qzrHJU+eSMJbds+MEmsY="
addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - openssl aes-256-cbc -K $encrypted_da608eb2506c_key -iv $encrypted_da608eb2506c_iv -in codenamephp.pem.enc -out codenamephp.pem -d

script:
  - chef exec rake
  
before_deploy:
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@codename-php.de"
  - git remote set-url --push origin "https://$GH_TOKEN@github.com/codenamephp/chef.cookbook.apache2.git"
deploy:
  - provider: script
    on:
      branch: master
    skip_cleanup: true
    script: chef exec rake release
  
notifications:
  slack: codenamephp:4LpipONUdfAZ5ebatYC7Egmb
